env:
    browser: true
    es2021: true
extends:
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:vue/recommended'
    - airbnb-base
parserOptions:
    ecmaVersion: 12
    parser: '@typescript-eslint/parser'
    sourceType: module
plugins:
    - vue
    - '@typescript-eslint'
    - prettier
rules:
    import/extensions:
        - error
        - ignorePackages
        - js: never
          jsx: never
          ts: never
          tsx: never
    semi: off
    '@typescript-eslint/semi':
        - error
    max-len:
        - error
        - code: 120
settings:
    import/resolver:
        node:
            extensions: ['.js', '.jsx', '.ts', '.tsx', '.d.ts']
