App\Entity\Color:
    attributes:
        id:
            groups: ['color:read', 'fabric:read']
        name:
            groups: ['color:read', 'color:write', 'fabric:read']
        code:
            groups: ['color:read', 'color:write', 'fabric:read']
        fabrics:
            groups: ['color:read']
