App\Entity\User:
    attributes:
        uuid:
            groups: ['user:read']
        username:
            groups: ['user:read', 'user:write']
        email:
            groups: ['user:read', 'user:write']
        emailConfirmation:
            groups: ['user:write']
        roles:
            groups: ['admin:write']
        plainPassword:
            serialized_name: password
            groups: ['user:write']
        passwordConfirmation:
            groups: ['user:write']
        code:
            groups: ['user:write']
