App\Entity\Code:
    attributes:
        security: 'is_granted("ROLE_ADMIN")'
    collectionOperations:
        get:
            normalization_context:
                groups: ['code:read']
        post:
            denormalization_context:
                groups: ['user:write']
    itemOperations:
        get:
            normalization_context:
                groups: ['code:read']
        put:
            denormalization_context:
                groups: ['code:write']
        delete: ~
