App\Entity\Fabric:
    attributes:
        security: 'is_granted("ROLE_USER")'
    collectionOperations:
        get:
            normalization_context:
                groups: ['fabric:read']
        post:
            denormalization_context:
                groups: ['fabric:write']
    itemOperations:
        get:
            normalization_context:
                groups: ['fabric:read']
        put:
            denormalization_context:
                groups: ['fabric:write']
        delete: ~
